### ISSUE TITLE
back's page need data update?

### ISSUE THREAD

**Issue by ijry** [nolimits4web/Framework7-Vue#186] opened 2017-06-05 05:36 UTC
when i back to pre page,  such as login.vue back to usercenter.vue. the pre page need tobe updated, but f7's route  read the dom's cache on-the-left, this confused me ?

**Comment by ijry** [comment] 2017-06-13 09:15
please ， this  is  urgent !

**Comment by ijry** [comment] 2017-06-13 09:17
this.$router.back({ignoreCache:true});   this ignoreCache:true never work which maker me wonder.

**Comment by araimbekoff** [comment] 2017-06-14 07:10
try it this.$router.back({iurl:'page-name'});

**Comment by ijry** [comment] 2017-06-16 03:43
@araimbekoff  never worked!

**Comment by araimbekoff** [comment] 2017-06-16 04:06
sorry!
`this.$router.back({url:'page-name', force:true});`
[Watch here](http://framework7.io/docs/router-api.html)

or
`this.$router.reloadPreviousPage(url)`

**Comment by ijry** [comment] 2017-06-16 04:16
never worked all of this, so i compused!

**Comment by ijry** [comment] 2017-06-16 04:16
the back's options seems  never got received

**Comment by ijry** [comment] 2017-06-16 04:22
![qq 20170616122115](https://user-images.githubusercontent.com/3102798/27211797-653c59b8-528e-11e7-9f21-099ab23bbca4.png)

the back method can only  got those prams.

**Comment by ijry** [comment] 2017-06-16 04:23
whatever you pass url force or something else ,you will not see it in back method's options.

**Comment by ijry** [comment] 2017-06-22 14:03
@araimbekoff

**Comment by ijry** [comment] 2017-06-22 14:03
i donnot what happened with my route!!

**Comment by nolimits4web** [comment] 2017-09-07 13:52
Duplicate of #201

**Closed by nolimits4web** 2017-09-07 13:52 UTC
