### ISSUE TITLE
$router.back  failed update page-on-left to page on center

### ISSUE THREAD

**Issue by ijry** [nolimits4web/Framework7-Vue#198] opened 2017-06-22 13:08 UTC
this.$router.back({force: true, url: '/user/index/index/'});

![qq 20170622202752](https://user-images.githubusercontent.com/3102798/27435428-d138dc22-578e-11e7-8b36-7248ba06c47f.png)

**Comment by nolimits4web** [comment] 2017-09-07 13:51
Duplicate of #201

**Closed by nolimits4web** 2017-09-07 13:51 UTC
