### ISSUE TITLE
:domCache="false" is conflit with this.$router.back({force: true, url: '/user/index/index/'});

### ISSUE THREAD

**Issue by ijry** [nolimits4web/Framework7-Vue#211] opened 2017-07-08 12:21 UTC
:domCache="false" is conflit with this.$router.back({force: true, url: '/user/index/index/'});

only set domCache=true, it work fine.

**Comment by nolimits4web** [comment] 2017-09-07 13:51
Duplicate of #201

**Closed by nolimits4web** 2017-09-07 13:51 UTC
